import "@/assets/globals.css";
import { Poppins } from 'next/font/google';
import { AuthProvider } from "@/context/Authcontext";


const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ['100', '300', '400', '700'],
  display: "swap",
});


export const metadata = {
  title: "Ringo",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${poppins.variable} font-sans bg-gray-100 text-gray-900 antialiased`}
      >
        <AuthProvider>
        <div className="">
          {children}
        </div>
        </AuthProvider>
      </body>
    </html>
  );
}
